version: '2'
services:
  # 服务名称
  nginx:
    # 镜像:版本
    image: nginx:latest
    container_name: blog_frontend
    restart: always
    # network_mode: 'host'
    # 映射容器80端口到本地80端口
    ports:
      - '80:80'
      # 数据卷 映射本地文件到容器
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - ./log:/var/log/nginx
      - ./ssl:/etc/nginx/ssl
    command: /bin/bash -c "nginx -g 'daemon off;'"
#     networks:
#       - data_application
# networks:
#   data_application:
#     external: true
